name: exercise8-nacc-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scikit-learn>=1.0.0
  - pip
  - pip:
    - nilearn>=0.9.0
    - ipywidgets>=7.6.0